USE kubyemek;
START TRANSACTION;

TRUNCATE TABLE admins;
ALTER TABLE admins ADD COLUMN username VARCHAR(255) NOT NULL UNIQUE AFTER id;

ALTER TABLE products MODIFY COLUMN image_url TEXT NOT NULL;

COMMIT;
